-- Table: public.users_app_user

-- DROP TABLE IF EXISTS public.users_app_user;

CREATE TABLE IF NOT EXISTS public.users_app_user
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(15) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    gender character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_app_user_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_app_user_email_key UNIQUE (email),
    CONSTRAINT users_app_user_phone_number_key UNIQUE (phone_number)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users_app_user
    OWNER to postgres;
-- Index: users_app_user_email_3518d605_like

-- DROP INDEX IF EXISTS public.users_app_user_email_3518d605_like;

CREATE INDEX IF NOT EXISTS users_app_user_email_3518d605_like
    ON public.users_app_user USING btree
    (email COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: users_app_user_phone_number_c9906629_like


-- DROP INDEX IF EXISTS public.users_app_user_phone_number_c9906629_like;

CREATE INDEX IF NOT EXISTS users_app_user_phone_number_c9906629_like
    ON public.users_app_user USING btree
    (phone_number COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;